「エディション移行」の翻訳をアップデート
rust-lang-ja/edition-guide pull request #45
Opened 2021-11-03 14:39 UTC by TonalidadeHidrica

Closes #26

2021-11-03 14:40 UTC, TonalidadeHidrica commented
おそらく `mdbook-transcheck` のバグで、最後の行に関して以下のエラーが出ます：

```
Error: lines has been removed from the source file
 target --> src/editions/transitioning-an-existing-project-to-a-new-edition.md:192
    |
192 | [nightly channel]: ../../book/appendix-07-nightly-rust.html
    |
```

（英語側で、最後の行に newline がないことが原因かと思われます）

2021-11-04 11:03 UTC, dalance commented
@TonalidadeHidrica
 ご指摘の点、mdbook-transcheckのバグでした。ありがとうございます。
修正したものを v0.2.7 としてリリースしました。

2021-11-04 15:32 UTC, TonalidadeHidrica commented
@dalance 差分が出なくなりました！　大変ありがとうございます。

2021-11-06 11:25 UTC, tatsuya6502 requested changes
2点コメントしましたので、ご確認ください。 [nits] は些細なものなので無視されても結構です。

よろしくお願いします。

2021-11-06 11:25 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
>  あなたのコードは互換性のない機能を使っているかも知れないし、使っていないかも知れません。
[nits] 今回の翻訳箇所ではありませんが、言葉が抜けてることに気づいたので。

```suggestion
あなたのコードは新しいエディションに互換性のない機能を使っているかもしれないし、使っていないかもしれません。
```

2021-11-06 11:25 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +cargo には [`cargo fix`] というサブコマンドがあり、これがあなたのコードを自動的に更新して Rust 2018 への移行を補助してくれます。
```suggestion
cargo には [`cargo fix`] というサブコマンドがあり、これがあなたのコードを自動的に更新して次のエディションへの移行を補助してくれます。
```

2021-11-06 12:14 UTC, TonalidadeHidrica commented
@tatsuya6502 レビューありがとうございます。2点ともご提案の通り訂正しました。

2021-11-06 12:20 UTC, tatsuya6502 approved these changes
レビューOKですのでマージします。おつかれさまでした！

2021-11-06 12:20 UTC, merged