「デフォルトの cargo のフィーチャリゾルバ」を翻訳
rust-lang-ja/edition-guide pull request #48
Opened 2021-11-04 07:14 UTC by TonalidadeHidrica

「デフォルトの cargo のフィーチャリゾルバ」を翻訳しました。一部だけ、わからない場所があります。

2021-11-06 12:45 UTC, tatsuya6502 requested changes
いくつかコメントしましたのでご確認ください。host dependenciesの謎も解けたと思います。

[nits] は些細なものなので、無視されても結構です。

2021-11-06 12:45 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +こうすると、cargo は出力の「フォーマット」を変更して、パッケージと有効化されているフィーチャの双方を表示するようになります。
[nits]

```suggestion
こうすると、Cargo は出力の「フォーマット」を変更して、パッケージと有効化されているフィーチャの双方を表示するようになります。
```

2021-11-06 12:46 UTC, TonalidadeHidrica commented on src/rust-2021/default-cargo-resolver.md
> +`cargo fix --edition` でのアップデート時に、cargo は新しいリゾルバで依存先のフィーチャに変更があるかどうかを表示します。
@tatsuya6502 こちら、個人的には日本人にとっては cargo を小文字で始めるほうが一般的だろうと思ったのですが、いかがでしょうか？　英語圏で Cargo と capitilize するのは、一般名詞の cargo と混同を避けるためであると推測します。一方で日本語では混同する恐れがないので、 cargo でいいかなと思いました。

2021-11-06 12:47 UTC, TonalidadeHidrica commented on src/rust-2021/default-cargo-resolver.md
> +これにより、 cargo はホスト依存関係<!--TODO: ホスト依存関係とは何ですか-->（proc-macro と build-dependencies）のフィーチャとして "postgres" を追加します。
へぇ〜、これは初耳ですね。ありがとうございます。

2021-11-06 13:02 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +これにより、 cargo はホスト依存関係<!--TODO: ホスト依存関係とは何ですか-->（proc-macro と build-dependencies）のフィーチャとして "postgres" を追加します。
proc macroはコンパイラのプラグインとして動作するので、ホスト向けにビルドされるんです。build-dependenciesも`build.rs`とリンクされてコンパイル前に実行されるのでホスト向けにビルドする必要があります。

このことは`cargo build`で`--target ターゲットトリプル`を指定すると確認できます。ビルドの成果物は`./target/ターゲットトリプル/debug/`配下に作られますが、proc macroの成果物（コンパイラプラグイン）などは`./target/debug/`配下に作られます。

2021-11-06 13:14 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +`cargo fix --edition` でのアップデート時に、cargo は新しいリゾルバで依存先のフィーチャに変更があるかどうかを表示します。
個人的には小文字で始めるほうが一般的、という認識はないです。Cargoはプロダクト名なので、その通りに表記するべきかなと思いました。

念のため手元の書籍・雑誌記事を確認したところ、以下のようになってました。
- Software Design誌 2021年9月号
    - 「ITエンジニア必須の最新用語解説」→ Cargo（大文字）
    - 「Rustでわかるメモリ管理」→ 「コンパイラをインストールしたあとはビルドツールであるcargoが使えることを確認して...」（小文字）
- 基礎から学ぶ組み込みRust → Cargo（大文字）
- Software Design誌 2020年6月号「入門！Rust」 → Cargo（大文字）
- インターフェース誌 2020年5月号「ついに登場!? C/C++以外の選択肢 Rustの研究」 → Cargo（大文字）

2021-11-06 13:20 UTC, TonalidadeHidrica commented on src/rust-2021/default-cargo-resolver.md
> +`cargo fix --edition` でのアップデート時に、cargo は新しいリゾルバで依存先のフィーチャに変更があるかどうかを表示します。
なるほど、日本語文献でも Cargo と表記するのが一般的なのですね。失礼いたしました。大文字表記に統一いたします。

2021-11-06 13:40 UTC, tatsuya6502 requested changes
すみません。前回の私が提案した修正内容に不備がありました。もう一度だけ修正をお願いします。

2021-11-06 13:40 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +これで、 `diesel_migrations` の手続き的マクロは "postgres" フィーチャが有効化された状態で走り、正しくビルドされます。
すみません。訳注のあとに改行がなくて、その後の本文とくっついてしまいました。改行の追加をお願いします。

```suggestion
> 一方、通常の依存関係はコンパイルターゲットのプラットフォーム向けにビルドされます。

これで、 `diesel_migrations` の手続き的マクロは "postgres" フィーチャが有効化された状態で走り、正しくビルドされます。
```

----

![comment](https://user-images.githubusercontent.com/159403/140611706-b3359523-7d32-4d8d-9111-5bf849bec83d.png)

https://94-144807784-gh.circle-artifacts.com/0/docs/rust-2021/default-cargo-resolver.html

2021-11-06 13:42 UTC, TonalidadeHidrica commented
こちらこそ確認不足でした。今度は大丈夫だと思います

2021-11-06 13:43 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

2021-11-06 13:43 UTC, merged

2021-11-11 01:21 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +```
見逃してました...。そうですね。修正していただけると助かります。

ところで、先ほど英語版のmasterの内容をupstream-masterブランチにマージしたのですが、このページに英語のタイポの修正が入っていました。和訳には影響なく、HTMLコメント内の原文の修正だけになりますが、ついでにそちらも反映してもらえないでしょうか？ https://github.com/rust-lang-ja/edition-guide/commit/84ccbc0cd6913d6ccce4c5feccdd28e3ce245594

2021-11-11 01:23 UTC, TonalidadeHidrica commented on src/rust-2021/default-cargo-resolver.md
> +```
@tatsuya6502 了解です。ちなみに、この2つのtypoは実は私が翻訳の過程で見つけたものです😀

2021-11-11 01:26 UTC, tatsuya6502 commented on src/rust-2021/default-cargo-resolver.md
> +```
おー、そうだったんですね。素晴らしい 👏