「クロージャはフィールドごとにキャプチャする」を翻訳
rust-lang-ja/edition-guide pull request #50
Opened 2021-11-04 10:49 UTC by TonalidadeHidrica

Closes #32

"disjoint capture" の訳語は迷いました。"disjoint" （(集合などが)素な）という意味の簡潔な日本語がないからです。
本文中では結局わかりやすく「フィールドごとのキャプチャ」と訳してみました。
同じ理由でタイトルも迷いました。上記と統一すれば「クロージャのフィールドごとのキャプチャ」なのですが、語感が悪くてわかりにくいので、あえて現行のものにしてみました。コメントでいくつかの代案を示しています。

一箇所、何を意味しているのかわからない箇所もありましたので、コメントにて示してあります。

2021-11-04 10:51 UTC, TonalidadeHidrica commented
最終行の改行が誤検知される `mdbook-transcheck` のバグから、差分が1つ消えていません。

2021-11-04 15:25 UTC, TonalidadeHidrica commented
`mdbook-transcheck` の [`v0.2.8`](https://github.com/dalance/mdbook-transcheck/blob/master/CHANGELOG.md#v028---2021-11-04) で @.dalance さんが修正していただいたため、差分が出なくなりました！　ありがとうございます。

2021-11-12 10:11 UTC, tatsuya6502 requested changes
TODOのところを含め、何点かコメントしました。ご確認ください。

2021-11-12 10:11 UTC, tatsuya6502 commented on src/rust-2021/disjoint-capture-in-closures.md
> +クロージャが変数 `t` の所有権を取るとき、`t` がドロップされるのは `t` がスコープ外に出たときではなく、そのクロージャがドロップされたときになります:
```suggestion
クロージャが変数 `t` の値の所有権を取るとき、その値がドロップされるのは `t` がスコープ外に出たときではなく、そのクロージャがドロップされたときになります:
```

2021-11-12 10:11 UTC, tatsuya6502 commented on src/rust-2021/disjoint-capture-in-closures.md
> +しかし、`Drop` の実装に副作用のある（いわゆるデストラクタである）場合、ドロップの順序が変わるとプログラムの意味も変わってしまいます。
[nits]

```suggestion
しかし、`Drop` の実装に副作用のある（いわゆるデストラクタである）場合、ドロップの順序が変わるとプログラムの意味が変わってしまうかもしれません。
```

"can alter" なので。（元の訳でも問題ないと思いますが）

2021-11-12 12:59 UTC, TonalidadeHidrica commented on src/rust-2021/disjoint-capture-in-closures.md
> +# クロージャはフィールドごとにキャプチャする <!-- 代案: クロージャのフィールドごとのキャプチャ、クロージャの非交差キャプチャ、クロージャの素(集合)キャプチャ -->
TODO: 代案コメントを削除

2021-11-12 13:00 UTC, TonalidadeHidrica commented on src/rust-2021/disjoint-capture-in-closures.md
> +  - `cargo fix` は、可能だと判断したときに、 `let _ = &a` のような文を挿入して、クロージャが変数全体をキャプチャするように強制します。
おっと、これは誤訳でした。TODO: 「このような違いが起こりうると検出したときに」にしてみます。

2021-11-12 13:31 UTC, tatsuya6502 requested changes
すいません。もう2点気づいたことがあって、それらも修正願います。（1つはリンク切れで原文の方の問題です）

2021-11-12 13:31 UTC, tatsuya6502 commented on src/rust-2021/disjoint-capture-in-closures.md
> +    // `x` 全体が強制的にキャプチャされるための "ダミーの let"
> "ダミーの let"

このページの下の方では

> 「ダミーの let」

になっていることに気づきました。

後者に統一しましょう。

```suggestion
以下のような状況を検知すると、`cargo fix` は「ダミーの let」をクロージャの中に挿入して、強制的に全ての変数がキャプチャされるようにします:

```rust
let x = (vec![22], vec![23]);
let c = move || {
    // "Dummy let" that forces `x` to be captured in its entirety
    // `x` 全体が強制的にキャプチャされるための「ダミーの let」
```

2021-11-12 13:31 UTC, tatsuya6502 commented on src/rust-2021/disjoint-capture-in-closures.md
> +[`unwindsafe`]: https://doc.rust-lang.org/std/marker/trait.UnwindSafe.html
原文の問題ですが、リンク切れになってます。

正しくは、

```suggestion
[`unwindsafe`]: https://doc.rust-lang.org/std/panic/trait.UnwindSafe.html
```

原文の対しては、後ほど、私からPRを提出しておきます。

2021-11-12 14:24 UTC, tatsuya6502 commented on src/rust-2021/disjoint-capture-in-closures.md
> +[`unwindsafe`]: https://doc.rust-lang.org/std/marker/trait.UnwindSafe.html
PRを提出しました。 https://github.com/rust-lang/edition-guide/pull/273

2021-11-12 15:19 UTC, TonalidadeHidrica commented
@tatsuya6502 終わりました。感謝です！

2021-11-12 15:24 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！！

2021-11-12 15:28 UTC, merged