「Cargo への変更」を翻訳
rust-lang-ja/edition-guide pull request #69
Opened 2021-11-12 16:15 UTC by TonalidadeHidrica

Closes #43 

#67 と同様、原文の情報を補足する目的で大幅に訳注を記述しています。
もしご負担でなければ、間違いがないかどうかチェックしていただけると幸いです。
もしチェックがご負担であれば、訳注をすべて削除しても構いません。

よろしくお願いいたします。

2021-11-16 12:31 UTC, tatsuya6502 commented on src/rust-2018/cargo.md
> +  [WIP] 詳細は不明です。
>   [WIP] 詳細は不明です。

[この辺のコード](https://github.com/rust-lang/cargo/blob/9e2790f828ddfe28c57024b6122ebaa6f31d9202/src/cargo/util/toml/targets.rs#L314-L321) が関係してそうですね。

```rust
            if let Some(legacy_path) = legacy_bin_path(package_root, &bin.name(), has_lib) {
                warnings.push(format!(
                    "path `{}` was erroneously implicitly accepted for binary `{}`,\n\
                     please set bin.path in Cargo.toml",
                    legacy_path.display(),
                    bin.name()
                ));
                Some(legacy_path)
```

その辺から辿っていったら、説明を見つけました！

https://github.com/rust-lang/cargo/pull/4259#issuecomment-314138552

> Sure! There are several cases, which I think are "accidental" and are deprecated here
> 
> - if you have a `[lib] name = "foo"` in your Cargo.toml, we treated `src/foo.rs` as a crate root. The fix is either to set path or to rename `src/foo.rs` to `src/lib.rs`.
> 
> - if you don't have a library, but you have `[bin] name = "foo"`, we treated `src/foo.rs` as a (binary) crate root. The fix is to add path or to move to `src/bin/foo.rs`.
>
> - if you have a `[bin] name = "bar"`, but your package's name is foo, we still treated `src/main.rs` or `src/bin/main.rs` as a bar's crate root, and now we warn. If binary names is the same as the package itself, then the behavior stays the same.

At least, these are all cases I intended to warn about, there maybe some unexpected stuff though!

2021-11-16 12:32 UTC, tatsuya6502 commented on src/rust-2018/cargo.md
> +  [WIP] 詳細は不明です。
@TonalidadeHidrica — 訳注 ^2 の詳細らしいissueコメントを見つけました！

2021-11-16 14:57 UTC, TonalidadeHidrica commented on src/rust-2018/cargo.md
> +  [WIP] 詳細は不明です。
@tatsuya6502 わざわざお手間をかけて調べてくださり、ありがとうございました！　まさにこれっぽいですね。追記します。

2021-11-17 09:49 UTC, tatsuya6502 requested changes
このページもたしかに訳注がないと、なんのことだかよくわかりませんね。調査していただき、ありがとうございます。

2点コメントしましたのでご確認ください（内1つはnits）　よろしくお願いします。

2021-11-17 09:49 UTC, tatsuya6502 commented on src/rust-2018/cargo.md
> +  これは、[*ターゲットの自動探索*][target-auto-discovery]と呼ばれています。<br>
[nits]

```suggestion
  これは、[ターゲットの自動探索][target-auto-discovery]と呼ばれています。<br>
```

macOSで表示すると「ターゲットの自動探索」のリンク（青文字）＋強調文字（太字）が変に目立って浮いた感じになっています。強調はなくてもよさそうに思いますがいかがでしょうか？

----

![cargo-changes-footnots pnd](https://user-images.githubusercontent.com/159403/142176704-55fcc647-a6f0-4848-b29f-23444f3b9cfb.png)

2021-11-17 09:49 UTC, tatsuya6502 commented on src/rust-2018/cargo.md
> +[target-auto-discovery]: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-path-field
```suggestion
[target-auto-discovery]: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#target-auto-discovery
```

2021-11-17 10:34 UTC, TonalidadeHidrica commented on src/rust-2018/cargo.md
> +  これは、[*ターゲットの自動探索*][target-auto-discovery]と呼ばれています。<br>
@tatsuya6502 たしかにそのとおりですね。修正しました。

2021-11-17 10:51 UTC, tatsuya6502 approved these changes
レビューOKですのでマージします。おつかれさまでした！

2021-11-17 10:52 UTC, merged