What are editions
rust-lang-ja/edition-guide pull request #8
Opened 2021-01-01 00:39 UTC by ksato9700

"What are editions?" セクションを訳してみました。先にPRした #7 を先にマージしていただくとコンフリクトなくマージできると思います。

2021-04-03 02:34 UTC, tatsuya6502 commented
@ksato9700 — レビューが遅くて大変申し訳ないです。

いまの状態ですと [diffが多すぎて](https://github.com/rust-lang-ja/edition-guide/pull/8/files) レビューできません。お手数ですが、最新のrust-lang-ja/edition-guideのmasterブランチの内容をksato9700/edition-guideのwhat-are-editionsブランチへマージしていただけないでしょうか？

例：
```console
$ cd ksato9700/edition-guideのwhat-are-editionsがcheckoutされているディレクトリー

## upstream/masterをマージする（rust-lang-ja/edition-guideがgit remoteに
## upstreamという名前で登録されている場合）
$ git pull upstream/master

## コンフリクトがあったら対応する

## what-are-editionsブランチへpushする
$ git push origin what-are-editions
```

よろしくお願いします。

2021-04-03 07:05 UTC, ksato9700 commented
@tatsuya6502 
承知しました。rebaseしてみます。

2021-04-03 08:11 UTC, ksato9700 commented
@tatsuya6502
rebaseしました。ご確認をお願いします m(_._)m

2021-04-04 01:24 UTC, tatsuya6502 requested changes
Rebaseしていただき、ありがとうございました！　非常に助かりました。

まだレビューの途中（日本語の部分をざっと読んだだけ）ですが、いったんここでお返しします。何点かコメントしましたので、ご確認と修正をお願いします。（事前に伝えてないことばかりで申し訳ないです）

2021-04-04 01:24 UTC, tatsuya6502 commented on src/editions/index.md
> +Rustは6週間ごとにリリースを行います。これにより、ユーザーは新しい機能を常に手に入れることができます。これは他の言語よりも速いサイクルですが、アップデートのサイズは小さくなります。しばらくするとこれらの小変更が積み重なってきますが、いくつかのリリースを振り返って、「おお、バージョン1.10から1.20の間にRustは大きく変わったなぁ」と言うのは難しいかも知れません。
Markdown上の1行が長くなると今後の更新でdiffが見づらくなるので、適宜、改行してください。ただ、改行の都度HTMLに半角スペースが入ってしまいますので、文の途中では改行せず、句点（。）のあとで改行して下さい。

例：

```suggestion
Rustは6週間ごとにリリースを行います。
これにより、ユーザーは新しい機能を常に手に入れることができます。
これは他の言語よりも速いサイクルですが、アップデートのサイズは小さくなります。
しばらくするとこれらの小変更が積み重なってきますが、いくつかのリリースを振り返って、「おお、バージョン1.10から1.20の間にRustは大きく変わったなぁ」と言うのは難しいかも知れません。
```

今後、翻訳の指針のような文章を作らないといけないですね。参考「the-rust-programing-language-ja &mdash; [翻訳時の指針][howto]」（ただし、この内容も古く、すでに現状と異なってます）

[howto]: https://github.com/rust-lang-ja/the-rust-programming-language-ja/blob/master/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E6%99%82%E3%81%AE%E6%8C%87%E9%87%9D

2021-04-04 01:24 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +`Cargo fix`は常に自動的にコードを修正してくれるわけではありません。もし、`cargo fix`がコードを修正できない時にはコンソールに修正できなかったというウォーニングを表示します。その場合は手動でコードを修正してください。助けが必要な時は、このガイドの対応するセクションを参照してください。問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.o
ウォーニングを表示します
　　↓
警告を表示します

対訳表（TranslationTable.md）では「ウォーニング」になっていますが、TRPL日本語版の訳を確認したところ「警告」に統一されていました。いろいろと後から言って申しわけないのですが、Edition Guideでも「警告」を使用しましょう。（対訳表も直してください）

参考：TRPL日本語版にも [issueを作成](https://github.com/rust-lang-ja/book-ja/issues/146) しました。

2021-04-04 01:24 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +`Cargo fix`は常に自動的にコードを修正してくれるわけではありません。もし、`cargo fix`がコードを修正できない時にはコンソールに修正できなかったというウォーニングを表示します。その場合は手動でコードを修正してください。助けが必要な時は、このガイドの対応するセクションを参照してください。問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.o
> 問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.org/)で助けを求めてください。

日本語コミュニティの情報も訳注として入れましょう。

例：

```Markdown
> 訳注：Rustの日本語コミュニティもあります。
> Slackを使用しており[こちら](https://rust-jp.herokuapp.com/)から登録できます。
```

2021-04-04 02:42 UTC, ksato9700 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +`Cargo fix`は常に自動的にコードを修正してくれるわけではありません。もし、`cargo fix`がコードを修正できない時にはコンソールに修正できなかったというウォーニングを表示します。その場合は手動でコードを修正してください。助けが必要な時は、このガイドの対応するセクションを参照してください。問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.o
対訳表も含めて修正しました。

2021-04-04 02:42 UTC, ksato9700 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +`Cargo fix`は常に自動的にコードを修正してくれるわけではありません。もし、`cargo fix`がコードを修正できない時にはコンソールに修正できなかったというウォーニングを表示します。その場合は手動でコードを修正してください。助けが必要な時は、このガイドの対応するセクションを参照してください。問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.o
日本語コミュニティの情報を追加しました。

2021-04-04 02:43 UTC, ksato9700 commented on src/editions/index.md
> +Rustは6週間ごとにリリースを行います。これにより、ユーザーは新しい機能を常に手に入れることができます。これは他の言語よりも速いサイクルですが、アップデートのサイズは小さくなります。しばらくするとこれらの小変更が積み重なってきますが、いくつかのリリースを振り返って、「おお、バージョン1.10から1.20の間にRustは大きく変わったなぁ」と言うのは難しいかも知れません。
句点の後で改行するようにしてみました。

2021-04-04 02:43 UTC, ksato9700 commented on src/editions/creating-a-new-project.md
> +configuration for the latest edition: -->
コメントアウトの仕方を修正しました。

2021-04-04 02:43 UTC, ksato9700 commented on src/editions/creating-a-new-project.md
> +<!-- # Creating a new project
コメントアウトの仕方を修正しました。

2021-04-04 02:45 UTC, ksato9700 commented
@tatsuya6502 
ご指摘の点を修正してみました。よろしくお願いいたします。

2021-04-04 03:32 UTC, tatsuya6502 commented on src/editions/creating-a-new-project.md
> +<!-- # Creating a new project
ありがとうございます

2021-04-04 03:32 UTC, tatsuya6502 commented on src/editions/index.md
> +Rustは6週間ごとにリリースを行います。これにより、ユーザーは新しい機能を常に手に入れることができます。これは他の言語よりも速いサイクルですが、アップデートのサイズは小さくなります。しばらくするとこれらの小変更が積み重なってきますが、いくつかのリリースを振り返って、「おお、バージョン1.10から1.20の間にRustは大きく変わったなぁ」と言うのは難しいかも知れません。
ありがとうございます

2021-04-04 03:33 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +`Cargo fix`は常に自動的にコードを修正してくれるわけではありません。もし、`cargo fix`がコードを修正できない時にはコンソールに修正できなかったというウォーニングを表示します。その場合は手動でコードを修正してください。助けが必要な時は、このガイドの対応するセクションを参照してください。問題がある場合は、 [ユーザーフォーラム](https://users.rust-lang.o
ありがとうございます

2021-04-04 04:33 UTC, tatsuya6502 requested changes
レビューしました。何点かコメントしましたのでご確認ください。

[nits]がついているコメントは軽微なものですので無視しても結構です。

2021-04-04 04:33 UTC, tatsuya6502 commented on src/editions/index.md
> +Rustのコンパイラはこれまでの全てのエディションをサポートしていて、どのエディションでもクレートをコンパイルすることができます。
> どのエディションでもクレートをコンパイルすることができます

原文は"can link crates of any supported editions together."ですので、以下のようにするのはどうでしょうか？

> 複数のクレートが異なるエディションを使用していても一緒にリンクできます。

2021-04-04 04:33 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +パラメータ名が追加された形でコードが書き換えられています。
```suggestion
トレイトオブジェクトのためのパラメータ名が追加された形でコードが書き換えられています。
```

2021-04-04 04:33 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +いずれ、`cargo fix`によってこのようなイディオムの変更も自動的に行いたいと考えています。
```suggestion
いずれ、`cargo fix`によってこのようなイディオムの変更も、2018エディションへアップグレードしたときのように自動的に行いたいと考えています。
```

2021-04-04 04:33 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +以下のコマンドでCargoがイディオムの修正を行います。
```suggestion
以上を踏まえたうえで、私たちのコード片の修正をCargoに行わせてみましょう。
```

2021-04-04 04:33 UTC, tatsuya6502 commented on src/editions/transitioning-an-existing-project-to-a-new-edition.md
> +Cargoのバグレポートを出すようにという恐ろしげな警告を見るかも知れませんが、これは `rustc`によって提案された修正が誤ってコンパイラを止めてしまった時に起こります。
> 提案された修正が誤ってコンパイラを止めてしまった

コンパイラが止まるですと`rustc`が止まることを想像しますが、原文は"a fix ... caused code to stop compiling by accident"なので、コードがコンパイルできなくなる（エラーを含んだコードになる）の意味に思えます。以下のようにするのはどうでしょうか？

> 提案された修正が誤ってコードをコンパイルできなくしてしまった

2021-04-04 10:20 UTC, ksato9700 commented
@tatsuya6502 丁寧なレビューありがとうございます。反映させてみました。

2021-04-04 10:29 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

p.s.
次回以降、ついでのときで構いませんので [src/SUMMARY.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/SUMMARY.md) に翻訳済みのページのタイトルを反映していただけないでしょうか？ 生成されたサイトの左側の目次にSUMMARY.mdの内容が表示されます。

2021-04-04 10:29 UTC, merged

2021-04-04 10:41 UTC, ksato9700 commented
ありがとうございます。そして [src/SUMMARY.md](https://github.com/rust-lang-ja/edition-guide/blob/master/src/SUMMARY.md) への反映も次回以降忘れないようにします。